export const dummyReviews = [
  {
    id: 1,
    title: "The Queen Lake of Kashmir",
    place: "Ratti Gali Lake",
    image: require("../images/post1.png"),
    description:
      "The Ratti Gali lake is alpine glacial lake in Neelum Valley Azad Kashmir, Pakistan at a height of 3700m ( 12130 feet). It is surrounded by glaciers almost all the year and these glaciers are the source of water in the lake. The road to its base camp is open usually from 1st week of August to mid October at the most. You have to stay either at Keran or Dewarin on Neelum road and have to hire a 4X4 vehicle to get there Or can stay at the base camp also. There are camps available on rent at base camp and one can use his/her own camp also as there is camping sites available. The bikers can also go up to base camp. The reasonable food and water is available at the base camp.The wash rooms are also available but not very clean . There are no wash rooms uphill after the base camp. From base camp to reach the lake, there are two options i:e either to go on horses or hike. The ride is about 25 minutes and the hike is about one hour on average. The traveling time from Keran to base camp is about 2.5 hours. There are hawkers on the lake providing tea, kashmiri qahwa and cold drinks and are very vigilant on cleanliness of the area. The beauty of lake is mesmerizing especially when there are wild flowers all around. There are no other activities except sight seeing . One must spent at least one hour there and enjoy the calmness of the area. There is hiking tract from Ratti gali towards Kaghan / Naran valley which touches at Browai on that side.There are about 5 lakes on this tract.",
    rating: 5,
    author: "Muhammad Hasan",
    date: "14 June 2022",
    hotelName: "Lake View Hotel",
    hotelCost: "5000",
    hotelRef: "03061781924",
    transportName: "XYZ Transportation Service",
    transportCost: "30000",
    transportRef: "03001254652",
  },
  {
    id: 2,
    title: "Must Visit in Kalam",
    place: "Ushu Forest Kalam",
    image: require("../images/post2.png"),
    description:
      "Visited Ushu Forest Kalam with family. Good place for day trip. Although there are camping facilities but these are not suitable for families due to lack of basic facilities. One can go there for lunch and to spent few hours. A large number of Dhabas for food are available there.",
    rating: 4,
    author: "Sufyan Sadiq",
    date: "07 Aug 2021",
    hotelName: "Lake View Hotel",
    hotelCost: "5000",
    hotelRef: "03061781924",
    transportName: "XYZ Transportation Service",
    transportCost: "30000",
    transportRef: "03001254652",
  },
  {
    id: 3,
    title: "Heart of Skardu",
    place: "Lower Kachura Lake",
    image: require("../images/post3.jpg"),
    description:
      "Now that the Northern Areas have been reopened for travel, our family scheduled a long overdue trip to the beautiful Skardu Valley to escape the heat of the plains. Skardu, located in the Gilgit-Baltistan province, is a bustling tourist destination and is often called the epitome of beauty, serenity and wilderness. Home to mountain peaks, majestic lakes and boundless forests, we were excited at the prospect of experiencing all that we could fit into a week, and the best way to start was to visit the famous Kachura Lakes.",
    rating: 4,
    author: "Owais",
    date: "01 Jan 2022",
    hotelName: "ABC Hotel",
    hotelCost: "5000",
    hotelRef: "03061781924",
    transportName: "XYZ Transportation Service",
    transportCost: "30000",
    transportRef: "03001254652",
  },
];
